# Prod environment configuration for Gateway Service
replicaCount: 2

image:
  repository: htcong104/gateway-service

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: prod.myapp.local
      paths:
        - path: /
          pathType: Prefix

config:
  appMessage: "API Gateway [PRODUCTION]"
  featureFlag: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi
