# Dev environment configuration for Gateway Service
replicaCount: 1

image:
  repository: htcong104/gateway-service

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: dev.myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dev.myapp.local
      secretName: dev-myapp-tls

config:
  appMessage: "API Gateway [DEV MODE]"
  featureFlag: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
