# Dev environment configuration for Order Service
replicaCount: 1

image:
  repository: conght/order-service

service:
  port: 8081

config:
  appMessage: "Order Service [DEV MODE]"
  featureFlag: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
