# Dev environment configuration for Order Service
replicaCount: 2

image:
  repository: htcong104/order-service

service:
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: dev.myapp.local
      paths:
        - path: /orders
          pathType: Prefix

config:
  appMessage: "Order Service [DEV MODE]"
  featureFlag: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
