# Cấu hình riêng cho Gateway Service
replicaCount: 1

image:
  repository: gateway-service
  tag: latest

service:
  type: LoadBalancer
  port: 80

config:
  appMessage: "Chào mừng đến với API Gateway!"
  featureFlag: false
