# Cấu hình riêng cho Inventory Service
replicaCount: 1

image:
  repository: inventory-service
  tag: latest

service:
  type: ClusterIP
  port: 8082

config:
  appMessage: "Dịch vụ Quản lý Kho hàng đang trực tuyến!"
  featureFlag: false

