# Cấu hình riêng cho Order Service
replicaCount: 1

image:
  repository: order-service
  tag: latest

service:
  type: ClusterIP
  port: 8081

config:
  appMessage: "Dịch vụ Quản lý Đơn hàng đang sẵn sàng!"
  featureFlag: true

