# Các giá trị mặc định cho microservices
replicaCount: 1

image:
  repository: my-app
  pullPolicy: Never # Mặc định dùng cho local Docker Desktop
  tag: ""

service:
  type: ClusterIP
  port: 8080

config:
  appMessage: "Chào mừng bạn đến với Microservice sử dụng Helm!"
  featureFlag: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

